# Set the min/max battery percent allowed
minPercent: 40
maxPercent: 80

# Registry subkey and value name to get and store the current charging status
regSubKeyName: SOFTWARE\BatteryMonitor
regValueName: Charging

# Domain to ping
domain: www.github.com

# Set your Tuya/IFTTT URLs to switch your smart plug. Leave them empty if you want a beep alert instead
onURL: ''
offURL: ''