#Set the min/max battery percent allowed
minPercent: 40
maxPercent: 85

#Registry key and value name to get and store the current charging status
regSubKeyName: SOFTWARE\BatteryMonitor
regValueName: Charging

#Set your Tuya/IFTTT URLs to switch your smart plug. Leave them empty if you want an unfocused "connect/disconnect" alert instead
offURL: ''
onURL: ''
